### ISSUE TITLE
Why chat history shows same message history for all the users?

### ISSUE THREAD

**Issue by riteshbathwal** [rpaschoal/ng-chat#101]
Hi I am using the Offline Bot Adapter. The issue that I face is that even if I  set my getMessageHistory() method lilke below, I am not getting different messages from UserID1 and UserID2 , infact I am getting same two messages for all the users. How should I configure message history so that different message history is shown in different message window?

getMessageHistory(userId: any): Observable<Message[]> {
        console.log("getMessageHistoryCalled --> Only Once");
        let mockedHistory: Array<Message>;

        mockedHistory = [                    
            {
                fromId: 1,
                toId: 999,
                message: "Hi there, just type any message bellow to test this Angular module."
            },
            {
                fromId: 2,
                toId: 999,
                message: "my custom msg"
            }
        ];

        return of(mockedHistory);
    }

**Comment by rpaschoal** [comment]
Hi @riteshbathwal ,

The offline bot is just a really simple example. You need to implement your own logic to fetch a user's history. You could for example send an API request with the userId to fetch the history from your application and then return its observable.

**Comment by riteshbathwal** [comment]
Got it, thanks

**Comment by MPTA** [comment]
hello , i have implemented my logic api and get messages from server but all messages shown in the left side , (the sender and receives Id already set and is correct information but shown is only in the left side)
