### ISSUE TITLE
I am wondering how to change avatar for a picture?

### ISSUE THREAD

**Issue by cristiantorresf19191919** [rpaschoal/ng-chat#109]
I am wondering how to change avatar for a picture?

**Comment by rpaschoal** [comment]
Hi @cristiantorresf19191919 ,

Use the `avatar` property of the `IChatParticipant` interface which is implemented by `User` or `Group`.

Cheers!

**Comment by cristiantorresf19191919** [comment]
excuse I am very new on coding can you PLEASE provide me an example I was lost with IChatParticipant interface it's like talking to me in Mandarin with hiccup

**Comment by rpaschoal** [comment]
Hi @cristiantorresf19191919 ,

Please check the following repositories for examples:

https://github.com/rpaschoal/ng-chat-netcoreapp
https://github.com/rpaschoal/ng-chat-nodejs
