### ISSUE TITLE
ng-chat Friend List in side menu 

### ISSUE THREAD

**Issue by Code-N-K** [rpaschoal/ng-chat#112]
Can we add ng-chat Friend List in side menu, as i have tried to add the friend list in side navigation menu of bootstrap either left or right side so that when require we can open the side navigation of chat, but it always open from below at bottom-right of page. Kindly Reply @rpaschoal .

**Comment by rpaschoal** [comment]
Hi @Code-N-K ,

Have you tried fiddling around with the custom themes option?

Shifting ng-chats position and chat window size is kinda of trick at the moment because there are a lot of view port calculations that happen intrinsically.
