### ISSUE TITLE
Friend List not Loaded

### ISSUE THREAD

**Issue by MuthiahMazzle** [rpaschoal/ng-chat#113]
I got this error on friend list loaded 
ERROR TypeError: Cannot read property 'avatar' of undefined
View_NgChat_7 @ ng:///NgChatModule/NgChat.ngfactory.js:145
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ vendor.js:63857
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ vendor.js:54427
(anonymous) @ vendor.js:57273
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.js:2710
push../node_modules/zone.js/dist/zone.js.Zone.run @ polyfills.js:2460
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ vendor.js:56468
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick @ vendor.js:57273
(anonymous) @ vendor.js:57158
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.js:2710
onInvoke @ vendor.js:56509
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.js:2709
push../node_modules/zone.js/dist/zone.js.Zone.run @ polyfills.js:2460
push../node_modules/@angular/core/fesm5/core.js.NgZone.run @ vendor.js:56423
next @ vendor.js:57158
schedulerFn @ vendor.js:56240
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ vendor.js:157933
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ vendor.js:157871
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ vendor.js:157815
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ vendor.js:157792
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ vendor.js:157558
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ vendor.js:56232
checkStable @ vendor.js:56478
onHasTask @ vendor.js:56522
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.hasTask @ polyfills.js:2763
push../node_modules/zone.js/dist/zone.js.ZoneDelegate._updateTaskCount @ polyfills.js:2783
push../node_modules/zone.js/dist/zone.js.Zone._updateTaskCount @ polyfills.js:2607
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ polyfills.js:2527
drainMicroTaskQueue @ polyfills.js:2917
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ polyfills.js:2822
ZoneTask.invoke @ polyfills.js:2807
timer @ polyfills.js:4376
Show 2 more frames
ng:///NgChatModule/NgChat.ngfactory.js:145 ERROR TypeError: Cannot read property 'avatar' of undefined

**Comment by rpaschoal** [comment]
Hi @MuthiahMazzle ,

It seems to me that something you're passing as a data source for your friends list is undefined. Please double check your API return or your test data.

**Comment by MuthiahMazzle** [comment]
thanks
