### ISSUE TITLE
I tried the Video Button by directly fork in ng-chat/fesm5/ng-chat.js file from node modules 

### ISSUE THREAD

**Issue by Code-N-K** [rpaschoal/ng-chat#116]
I tried the Video Button by directly fork in ng-chat/fesm5/ng-chat.js file from node modules. 

Image below
<img width="956" alt="chatVideo" src="https://user-images.githubusercontent.com/21154957/55801384-967f7900-5af3-11e9-9015-dc71d023b5fd.png">

but now i am not able to show them properly, and also the onVideoChatWindow(window) method throws error. Kindly update the same for your next build. Where Video (video Button) and X10(Close Button)  are shown. Kindly Help, as the layer provided by you is great, but these features are not allowing to add something new to ng-chat.  @rpaschoal

**Comment by rpaschoal** [comment]
Hi @Code-N-K ,

You shouldn't be updating the build files, those are JS bundles generated via ng-packgr.
