### ISSUE TITLE
How to save to DB on node and angular?

### ISSUE THREAD

**Issue by mosheDO** [rpaschoal/ng-chat#118]
I really need some help about save all messages to DB (mongo)
any help appricate

thanks!

**Comment by rpaschoal** [comment]
Hi @mosheDO ,

Managing the state of your message and users is up to your application. ng-chat is merely the interface to enable the flow of messages and data through users on an Angular application.

These links might be helpful (although there is no DB persistence) in case you haven't checked them:

https://github.com/rpaschoal/ng-chat-netcoreapp
https://github.com/rpaschoal/ng-chat-nodejs

Hope this helps!

Cheers

**Comment by mosheDO** [comment]
First of all thank you @rpaschoal  for the repo and the answer.

I already checked them and i still cant figure out how to add DB.
is there a chance to add DB in this example?

 https://github.com/rpaschoal/ng-chat-nodejs

**Comment by ajayshukla** [comment]
Any update on this mate?

I also want to do the same.

Thanks

**Comment by rpaschoal** [comment]
Hi @mosheDO and @ajayshukla ,

I don't have any plans in adding a demo that persists the messages on a database. The existing demos should be a fairly good kick-starter on how the data flows through your back-end and persisting the messages should be fairly straight forward if you've already got experience in writing APIs that persist data.

Cheers.
