### ISSUE TITLE
Linkfy - cannot click on links, see html code in chat.

### ISSUE THREAD

**Issue by Thorski** [rpaschoal/ng-chat#121]
Am I misunderstanding how the linkfyEnabled should work?   I was expecting to get a link I could click on in the chat window.  Instead I see html with the anchor tag.   I repeated this on your demo site.

![image](https://user-images.githubusercontent.com/28730875/56605785-df92fb00-65d2-11e9-8287-b9cd036c0729.png)

Very nice chat implementation! Thank you!

**Comment by rpaschoal** [comment]
Hi @Thorski ,

Thank you for reporting this, seems like a bug to me. I'll investigate further and see what is going on and release a patch version to fix this. I've got some planned work on potential minor/major releases that I still have to find some time for it (Quite busy recently =/) but I usually try to release bug patches as quick as I can. Please expect a patch release fixing this in the next couple days max.

I'll notify you here as soon I've released the new version.

Cheers!

**Comment by rpaschoal** [comment]
Hi @Thorski ,

I've released version `2.0.3` which contains the fix for this bug. You can check the changes I've made here if you are interested #123 

Cheers!

**Comment by Thorski** [comment]
Works great!  Thanks!
