### ISSUE TITLE
In SignalR demo issue with userId when uploading files

### ISSUE THREAD

**Issue by MuhammadRizwanBashir** [rpaschoal/ng-chat#124]
I was checking SignalR demo and uploaded files to someone in chat room. once i uploaded file to one user and then uploaded file to other user, but file sent to same user whom i sent before.
Maybe i have changed the focus, or on upload button userId is not changing. I haven't debugged yet. Maybe this is issue in just demo. I will update here after implementation.

**Comment by MuhammadRizwanBashir** [comment]
File only can be send to user we sent first, to send file to other user we have to close the chat window of previous user we have sent the file. There is issue in file upload.

**Comment by rpaschoal** [comment]
Hi @MuhammadRizwanBashir ,

Thank you for reporting this issue.

I'll investigate and if this is really a problem will come up with a patch release at some point this week.

Cheers!

**Comment by rpaschoal** [comment]
Hi @MuhammadRizwanBashir ,

Just letting you know that a fix for this issue has just been published to NPM with version `2.0.4`.

This is the pull request containing the changes #125 and here you can find the details of what was released with version `2.0.4`: https://github.com/rpaschoal/ng-chat/releases/tag/2.0.4

**Comment by MuhammadRizwanBashir** [comment]
@rpaschoal Thanks
