### ISSUE TITLE
Chat message user icon default showing. How can i set them

### ISSUE THREAD

**Issue by sachinbasendr** [rpaschoal/ng-chat#133]
My friend list showing all user icons but when on click user to open chat window all messages showing with default icons.

Is this possible for show user icon on chat window?

Please help?

**Comment by rpaschoal** [comment]
Hi @SachinJat ,

You have to set the avatar on the response of the participant details.

**Comment by SachinJat** [comment]
Hi @rpaschoal 

I am already set avatar on participant details of friend list.
but on chat list user icon not showing according to set avatar.
What i am missing?
Please see my chat room
![Screenshot](https://user-images.githubusercontent.com/40889887/63666992-cf449400-c7ef-11e9-8667-33835cd148e6.png)
