### ISSUE TITLE
New release and updated features 

### ISSUE THREAD

**Issue by Jeenalbhatt** [rpaschoal/ng-chat#135]
When will new feature release ? can you let us know what all features will be available in next release if possible

**Comment by rpaschoal** [comment]
Hi @Jeenalbhatt ,

I'm planning a patch release for within the next 2 weeks to fix the following issues:

https://github.com/rpaschoal/ng-chat/issues/120
https://github.com/rpaschoal/ng-chat/issues/127
https://github.com/rpaschoal/ng-chat/issues/134

and the changes on this PR: https://github.com/rpaschoal/ng-chat/pull/128

Mainly bug fixes. Is there any particular feature or idea you are looking for? Cheers

**Comment by rpaschoal** [comment]
Hi @Jeenalbhatt ,

https://github.com/rpaschoal/ng-chat/releases/tag/2.0.5 has just been released! 🎉
