### ISSUE TITLE
Status indicator not updated after Participant chat window opened

### ISSUE THREAD

**Issue by nesmrten** [rpaschoal/ng-chat#140]
Hi there,

Thanks for the repo. I just encountered the issue with status color indicator not updating on participant chat window after friendlist updated. See the attachment.
![chat indicator](https://user-images.githubusercontent.com/14312037/67634103-35b16580-f8b8-11e9-89bc-101b239d94ab.PNG)

Best regards,
Beki Lutolli

**Comment by rpaschoal** [comment]
Hi @nesmrten ,

Is your friend list fetching data via polling? If not you need to notify your adapter that the friends list has been changed.

Cheers

**Comment by nesmrten** [comment]
Thank you for your answer, i guess it was just a freelancer, who didn't know hot to properly implement chat :).

**Comment by wandersomMv** [comment]
thank you for answer.
