### ISSUE TITLE
How this module works

### ISSUE THREAD

**Issue by jsmitjans** [rpaschoal/ng-chat#142]
Where I can find the view of the directive <ng-chat> and it component?Someone can explain to me how the module works, because in the documentation it only says how to install it but not how to use it and adapt it to our needs.I don't understand what files i need to modify.Where I can find the components that use the main functions such as getMessageHistory. Please help me,I'm new with Angular and I need to implement a chat like this but I don't understand this module.

**Comment by rpaschoal** [comment]
Hi @jsmitjans ,

You're right, the documentation covers how to install the module and the available settings to integrate it with your application. There is no documentation on how it has been built apart from the code here on GitHub which is open source.

I do welcome pull requests from other developers but I have no plans on adding documentation on every single component that is part of this module. Hopefully by reading the code you or anyone else should be able to get a grasp on how things work and have been done.

There is documentation on how to get your develop environment set up if you want to contribute: https://github.com/rpaschoal/ng-chat/blob/master/CONTRIBUTING.md

Cheers
