### ISSUE TITLE
ng-chat.js:477 ng-chat component couldn't be bootstrapped.

### ISSUE THREAD

**Issue by shakthi-manai** [rpaschoal/ng-chat#143]
This issue has been reported earlier but it is closed.
So i am raising the issue again. 

ng-chat can't be bootstrapped without a ChatAdapter. Please make sure you've provided a ChatAdapter implementation as a parameter of the ng-chat component.

I have tried to use the example as is in my application.
except for that the component is not in the app-component class but a subclass called after login.

Ant kind of leads would be helpful

**Comment by rpaschoal** [comment]
Hi @shakthi-manai ,

In case you haven't, please check these repositories for further guidance:

https://github.com/rpaschoal/ng-chat-netcoreapp
https://github.com/rpaschoal/ng-chat-nodejs
