### ISSUE TITLE
ERROR: An accessor cannot be declared in an ambient context

### ISSUE THREAD

**Issue by glenelkins1984** [rpaschoal/ng-chat#154]
Hi

I've installed this library but it doesn't work! I just get the following errors:

```
ERROR in node_modules/ng-chat/ng-chat/ng-chat.component.d.ts(25,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/ng-chat/ng-chat/ng-chat.component.d.ts(26,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/ng-chat/ng-chat/ng-chat.component.d.ts(73,17): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/ng-chat/ng-chat/ng-chat.component.d.ts(74,9): error TS1086: An accessor cannot be declared in an ambient context.
```
I am using angular/core 8.2.14 and angular/cli 8.3.23

**Comment by rpaschoal** [comment]
Hello @glenelkins1984 ,

What version of Angular and Typescript are you using? I've recently released `3.0.0` which included upgrades on a lot of dependencies, including Typescript.

Here are the recently released changes: https://github.com/rpaschoal/ng-chat/pull/153/files 

I was about to merge this PR into `master` but was giving it a few days post release. Might be worthwhile waiting for your response before doing so.

**Comment by rpaschoal** [comment]
Hi @glenelkins1984 ,

ng-chat was recently upgraded to Angular 9 and it included a lot of dependencies upgrade too, Typescript included. Here are the changes that I am about to merge into `master`: https://github.com/rpaschoal/ng-chat/pull/153/files

If you don't want to upgrade your application at this stage, you could use one of the previous versions of ng-chat, version `2.0.5`.

Hope it helps, thanks!

**Comment by glenelkins1984** [comment]
@rpaschoal thanks!
