### ISSUE TITLE
thumbnail previews

### ISSUE THREAD

**Issue by rrpuente** [rpaschoal/ng-chat#157]
@rpaschoal 
I'm not sure if it will be acceptable, but it looks easy to achieve.
Just adding a new type of message (lets say Image=3), and modifying the template to have that type of message. It does not look greeaat, but it i an starting point.
<img width="301" alt="image" src="https://user-images.githubusercontent.com/31176623/81415162-58b2b100-9148-11ea-86ff-75d0fa689b77.png">

**Comment by rpaschoal** [comment]
Looks like it is getting there @rrpuente ,

Looking forward to seeing the PR to add this functionality! 🚀

**Comment by rpaschoal** [comment]
Just linking the pull request here: https://github.com/rpaschoal/ng-chat/pull/158

**Comment by rpaschoal** [comment]
This has been released with 3.0.2 @rrpuente
