### ISSUE TITLE
How to implement many to many chat window

### ISSUE THREAD

**Issue by sandys6294** [rpaschoal/ng-chat#164]
My problem is when I am creating a user using your command prompt I am able to create one user per chrome tab. But i want to create more than one user from the same tab and the communication should be based on the UserId instead of ConnectionId which i have changed but then also I am facing issue. Please help me with this genius.

**Comment by rpaschoal** [comment]
@sandys6294 I am unsure on how to help, but as far as I could understand from your message, I believe ng-chat might not be the best tool to solve your problem. This module was designed to be used by only one user per window/tab.
