### ISSUE TITLE
Error install in Angular7

### ISSUE THREAD

**Issue by MamartinBSW** [rpaschoal/ng-chat#165]
ERROR in node_modules/ng-chat/ng-chat/components/ng-chat-friends-list/ng-chat-friends-list.component.d.ts(30,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/ng-chat/ng-chat/ng-chat.component.d.ts(26,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/ng-chat/ng-chat/ng-chat.component.d.ts(27,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/ng-chat/ng-chat/ng-chat.component.d.ts(71,17): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by rpaschoal** [comment]
This module was upgraded to Angular 9 with release https://github.com/rpaschoal/ng-chat/releases/tag/3.0.0

You might be able to get it working with version https://github.com/rpaschoal/ng-chat/releases/tag/2.0.5 but I suggest you just upgrade your application.

**Comment by MamartinBSW** [comment]
> This module was upgraded to Angular 9 with release https://github.com/rpaschoal/ng-chat/releases/tag/3.0.0
> 
> You might be able to get it working with version https://github.com/rpaschoal/ng-chat/releases/tag/2.0.5 but I suggest you just upgrade your application.

Thanx  @rpaschoal 

I install this versión and now 
![Captura de pantalla 2020-06-26 a las 9 29 44](https://user-images.githubusercontent.com/52775528/85832048-a7b3b480-b78f-11ea-8b6c-b0d469ee8cf8.png)

`ERROR in src/app/components/perfil/perfil.component.ts(25,27): error TS2307: Cannot find module 'my-adapter'.`


Thnx!
