### ISSUE TITLE
Unread messages indicator in chat window and chat participants list does not updates when "MessagesSeen" triggered

### ISSUE THREAD

**Issue by victorz-airsoft** [rpaschoal/ng-chat#167]
Hi, first of all thank you for the greate package, it's very useful in our application.

Recently we have discovered the issue with "unread messages indicator" in chat window and chat participants list - when "MessagesSeen" event is triggered, they don't get updated and continue to grow. Update become seen only after we close and reopen the chat window. Put some screenshots for the issue.
![messagesSeen](https://user-images.githubusercontent.com/54435788/87872367-85910900-c9c0-11ea-991c-aeab168c0568.PNG)
![messageSeenFromDemo](https://user-images.githubusercontent.com/54435788/87872379-afe2c680-c9c0-11ea-8da3-3d00696244bb.PNG)

**Comment by rpaschoal** [comment]
Hi @victorz-airsoft ,

Thank you for raising this. I couldn't reproduce it on the online demo but I'll verify locally as I think the online demo is running a few versions behind from the most recently published package.

**Comment by rpaschoal** [comment]
Hi @victorz-airsoft ,

I've just tested locally with 3.0.3 and I couldn't reproduce. My messages counter was resetting as soon as I was clicked or tabbed a chat window into focus.

Could you confirm which version of ng-chat you are using, which base adapter type (Default or Paged) and perhaps provide a sandbox link (plunkr or similar) with the issue?

**Comment by victorz-airsoft** [comment]
Hi, thanks for reply. We use the 3.0.3. We will check everything again, maybe some conditions of our application have cause this issue. Thank you anyway
