### ISSUE TITLE
unable to see upload file button

### ISSUE THREAD

**Issue by canbrian** [rpaschoal/ng-chat#172]
Reproduce Steps:
1) clone the demo code v3.0.3
2) get the chat module running in 
Angular CLI: 10.0.5
Node: 12.16.3
OS: win32 x64
SignalR 1.1.0
3) Pick up one mockedParticipant to open chat window

Expected: an upload button exists to the right of the bottom bar or somewhere
![upload-button](https://user-images.githubusercontent.com/29160207/94346210-1572b500-fff9-11ea-96c3-1fecc47c0622.jpg)

Actual: the upload button doesn't exist

**Comment by rpaschoal** [comment]
Hi @canbrian ,

Have you supplied a `fileUploadUrl` argument to your ng-chat instance?

**Comment by canbrian** [comment]
Thanks, I got it by providing this argument.
