### ISSUE TITLE
I have problem with ng-chat it says error Can't bind to 'adapter' since it isn't a known property of 'ng-chat'.

### ISSUE THREAD

**Issue by chiragchande** [rpaschoal/ng-chat#176]
when I was join the room and this kind of error 
![ng-chat](https://user-images.githubusercontent.com/46920151/95963767-b77e0400-0e25-11eb-8ff4-ef815f01bd04.PNG)

**Comment by chiragchande** [comment]
please help me ! I got stcuk now !!

**Comment by rpaschoal** [comment]
Hi @chiragchande 

Please refer to these example projects:

https://github.com/rpaschoal/ng-chat-netcoreapp
https://github.com/rpaschoal/ng-chat-nodejs

Next time it might be a good idea to set up a reproduction sandbox environment or plunkr before reporting an issue so there's more details about the code that might be failing.

**Comment by chiragchande** [comment]
https://github.com/rpaschoal/ng-chat-nodejs  this one
