### ISSUE TITLE
Integrating with Slack API

### ISSUE THREAD

**Issue by morgangit** [rpaschoal/ng-chat#179]
Apologies for just posting a question here - but before I dive into this, has anybody tried to integrate this with Slack? I mean to have messages sent to some existing userID sent to a Slack channel and have replies posted on that channel appear as replies by that userID in browser instance.

Just wanted to check if you know of any reason that could not work.

**Comment by rpaschoal** [comment]
Hi @morgangit ,

This should be feasible if you have an API orchestrating the integration for you behind the scenes. You might be able to do it directly from your Angular application as well but that could expose your Slack API key I think.

**Comment by morgangit** [comment]
Ok, thank you @rpaschoal.
