### ISSUE TITLE
how can i paginate the messages 

### ISSUE THREAD

**Issue by amey2792** [rpaschoal/ng-chat#190]
how can i paginate the messages on a chat window 

when scroll to top can i load new messages ??

**Comment by rpaschoal** [comment]
Hi @amey2792 ,

Check out this example: https://github.com/rpaschoal/ng-chat/blob/master/demo/offline_bot/src/app/demo-adapter-paged-history.ts

Hope it helps!

**Comment by UdaramPrajapat** [comment]
@amey2792 could you please help me in implementation of getMessageHistoryByPage(destinataryId: any, size: number, page: number) 
This function is not being called automatically when i scroll top to see old chat history... how did you manged to get history by page
