### ISSUE TITLE
Firebase Implementation

### ISSUE THREAD

**Issue by Interscope19** [rpaschoal/ng-chat#195]
Good day i am trying to implement this package to my proyect but im using firebase im able to show the friendList and a list of messages but  it doesnt open the chat when new message is received or update the  chat window when user types... can u help me about?   
this is my current implementation in message history
![image](https://user-images.githubusercontent.com/82596162/129386295-50529292-abf2-4c54-bc29-ff9715c548ba.png)
method to get the message 
![image](https://user-images.githubusercontent.com/82596162/129386850-dc4be912-7667-4af0-a8f1-d7919105bb22.png)

and this is when i send a message 
![image](https://user-images.githubusercontent.com/82596162/129386522-4f32e0ba-ef2e-4b93-8c55-af49fafb63cc.png)
method to save in firebase
![image](https://user-images.githubusercontent.com/82596162/129386678-3b07fdf1-82c6-4265-adee-005d40b746c5.png)

 do i lost something ? about?

**Comment by rpaschoal** [comment]
This project has been archived and is no longer maintained.
