### ISSUE TITLE
Html tag does not show up!!!

### ISSUE THREAD

**Issue by fluttercid** [rpaschoal/ng-chat#197]
Hi Rpaschoal,
I appreciate your implementing this.
If I put <test> in an input window and when I sent it, an empty dialog is showed up in a chat window.
How can I display this text in a chat window?
Thank you for your answer in advance.

**Comment by fluttercid** [comment]
Hi Rpaschoal,
The last comment isn't a bit clear. 😀
When I put <text> to an input window and sent it, an empty dialog is showed up in a chat window;
however, a receiver can see the message through a chat server.
Is there any solution for it?
Thank you for your answer in advance.

P.S.: Does it have a security concern?

**Comment by rpaschoal** [comment]
This project has been archived and is no longer maintained.
