### ISSUE TITLE
onMessageReceived

### ISSUE THREAD

**Issue by elrondfeng** [rpaschoal/ng-chat#198]
I am using Angular, after the message is sent, I can see from log that the receiver's client side have the new message, however, the receiver's ui is not showing the new message. 

I haven't call onMessageReceived cause I don't know where to call it in Angular? should I call it from the adapter? if so, the adapter in angular is just a service, in which method should I call the onMessageReceived ?

**Comment by elrondfeng** [comment]
I figured it out. thanks!

**Comment by FractalMind** [comment]
> I figured it out. thanks!

Please, always share for people behind
