### ISSUE TITLE
ng build error

### ISSUE THREAD

**Issue by elrondfeng** [rpaschoal/ng-chat#200]
I forked the repo can try to build ng-chat locally. when I do ng build, I got this error: 
[error] Error: Cannot find module '@angular-devkit/build-angular/package.json'

what is the normal step to build ng-chat locally?

**Comment by styleanew** [comment]
I did npm install --legacy-peer-deps and it worked and then I got other errors.

**Comment by rpaschoal** [comment]
This project has been archived and is no longer maintained.
