### ISSUE TITLE
Pagination method not calling on scroll up.

### ISSUE THREAD

**Issue by devendralohar** [rpaschoal/ng-chat#201]
this getMessageHistoryByPage(destinataryId: any, size: number, page: number): method is not calling when I scroll move down to up to load more history data.
here is my configuration 
<ng-chat #ngChatInstance [adapter]="adapter" (onMessagesSeen)="messageSeen($event)" [historyEnabled]="true" [historyPageSize]="10" [hideFriendsList]="true" [emojisEnabled]="true" [userId]="userId"></ng-chat>

**Comment by rpaschoal** [comment]
This project has been archived and is no longer maintained.
