### ISSUE TITLE
Add icons to show message status

### ISSUE THREAD

**Issue by Thalysonb** [rpaschoal/ng-chat#202]
I'd like to be able to see the status of the message, represented by an icon, on the screen. Something like:

![Captura de Tela 2022-02-11 às 12 08 45](https://user-images.githubusercontent.com/34477333/153689840-c974874f-073c-49b9-b93d-f6709a752cbc.png)

These icons can be passed by parameters to ng-chat component, with the status type. I thought on something like this for example:

[
     {
        status: 'sent',
        icon: 'icon_url'
     }
]

Also  wold be nice if on this object we could pass an property to use when we need resend an message that was not sent, like on image above.

And finally, wold be nice if the library had a method to update the message history, to use when the message status change.

**Comment by rpaschoal** [comment]
This project has been archived and is no longer maintained.
