### ISSUE TITLE
Question Asp.Net Web API 2

### ISSUE THREAD

**Issue by JorgelGtzGtz** [rpaschoal/ng-chat#204]
Hello I tried to use the ng chat in web api 2 but I can't I received error from the ng chat not from the web api application I used the "Microsoft.AspNet.SignalR.Core" 2.4.3.0, The is not supported to web api application ?

This is the message  

Error while starting SignalR connection: Error: Detected a connection attempt to an ASP.NET SignalR Server. This client only supports connecting to an ASP.NET Core SignalR Server. See https://aka.ms/signalr-core-differences for details.

**Comment by rpaschoal** [comment]
This project has been archived and is no longer maintained.
