### ISSUE TITLE
@aspnet/signalr deprecated

### ISSUE THREAD

**Issue by avmesquita** [rpaschoal/ng-chat#205]
@aspnet/signalr deprecated.

There will be implementation to @microsoft/signal?

https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-6.0&tabs=visual-studio

https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-6.0

**Comment by avmesquita** [comment]
There is:

import { MessageType } from './message-type.enum';
export declare class Message {
    type?: MessageType;
    fromId: any;
    toId: any;
    message: string;
    dateSent?: Date;
    dateSeen?: Date;
}

But message is sending with "msg" property and not "message".

**Comment by avmesquita** [comment]
![image](https://user-images.githubusercontent.com/646271/157236153-95b6fe82-9f5c-42e7-9ee0-5fce611c8401.png)

**Comment by rpaschoal** [comment]
This project has been archived and is no longer maintained.
