### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by garyro** [rpaschoal/ng-chat#206]
Recently I upgraded an older project from ng 9 to 13 I'm havin an issue using the dark-theme.  The following is the error:
Error: src/app/chat/chat.component.html:5:4 - error TS2322: Type '"dark-theme"' is not assignable to type 'Theme'.

LIght theme or even custom theme is fine. Any help is appreciated

**Comment by rpaschoal** [comment]
This project has been archived and is no longer maintained.
