### ISSUE TITLE
How to refresh conversation?

### ISSUE THREAD

**Issue by FractalMind** [rpaschoal/ng-chat#210]
I want to sync the SAME participant across all Instances. If I open 2 instances of the same participant and I write something I can refresh the history storage of the second instance but I won't show any changes. When I call `this.getMessageHistory( FK_user_to_id );` it WONT execute the function.

![2022-04-20_18-17](https://user-images.githubusercontent.com/5481933/164334261-d718dc8f-c67a-4b12-915d-2305447d47d1.png)

I have to close the chat windows and reopen it to really call `getMessageHistory` and see the difference

![2022-04-20_18-18](https://user-images.githubusercontent.com/5481933/164334313-50bb93c2-99cd-45a6-8263-12e58e228aba.png)

Any thought on this? thanks!

**Comment by ShatteredCrown** [comment]
I was recently playing around with this module and found your question:
Once you extend the adapter class you have  access to amethod called OnMessageRecieved. I performed asynchronous polling in the frontend to check for updates and once I found a new Message I called adapter.OnMessageRecieved(...) for the appropriate participant and message which then triggers the notifications and updates.

**Comment by rpaschoal** [comment]
This project has been archived and is no longer maintained.
