### ISSUE TITLE
ChatController doesn't get instantiated

### ISSUE THREAD

**Issue by a-hosseini** [rpaschoal/ng-chat#212]
I have everything setup as instructed in the README file:

`<ng-chat #ngChatInstance [adapter]="adapter" [userId]="chatUserId"></ng-chat>
`
and in my component:
```
export class ChatComponent implements OnInit {
  @ViewChild('ngChatInstance')
  protected ngChatInstance: IChatController;
...

  ngOnInit(): void {
    this.ngChatInstance.triggerOpenChatWindow(this.mockedParticipants);
}
```

Everything works but the chat controller. `this.ngChatInstance` is the `ngOnInit` method comes back undefined.

Can you help me solve this please?

**Comment by rpaschoal** [comment]
This project has been archived and is no longer maintained.
