### ISSUE TITLE
message history

### ISSUE THREAD

**Issue by cprouveu** [rpaschoal/ng-chat#51]
Hello,

iIm trying to use your ng-chat on 42's school project but I can't understand how work the history chat by demo (offline chat).

I see history from id : 1 to id : 999 on every window.

Can you give me some help ?

Thanks.

**Comment by rpaschoal** [comment]
Hi @cprouveu,

Sure thing! Could you please post your chat adapter code here?

Cheers!

**Comment by cprouveu** [comment]
Just with your chat demo code i have this. I don t understand why i have the same history message on each windows while your demo code write 1 to 999. Normally it s just Aria who have the history.

**Comment by cprouveu** [comment]
Thanks for your answer, i understand why all users send the same history.
