### ISSUE TITLE
Minimize Chat

### ISSUE THREAD

**Issue by todd7** [rpaschoal/ng-chat#56]
Hello @rpaschoal 

This chat is amazing. 
Would it be possible for the chat to start minimize?

**Comment by rpaschoal** [comment]
Hi @todd7 ,

Thanks, I am glad you find it amazing! 

Yes, that is possible and it is a current feature. If you want the `Friends` list to start minimized, all you have to do is set the property `isCollapsed` to true.

EG: `<ng-chat OtherSettings... [isCollapsed]="true"></ng-chat>`

The chat stores the state of open windows onto the browser's local storage. This is enabled by default, and if the user reload the page or come back to it on another time, it will load the chats once again. In this case I believe the friends list will be minimized if `isCollapsed` is set to true, but the chat windows would be maximized. I will test this later on, it seems there is a space to improvement around this.

Let me know if this helped you out, cheers!

**Comment by todd7** [comment]
Hi @rpaschoal, helped me a lot, thanks !!!

**Comment by rpaschoal** [comment]
I am closing this as @todd7 questions were answered.
