### ISSUE TITLE
error TS2307: Cannot find module 'my-adapter'

### ISSUE THREAD

**Issue by aaithu-pk** [rpaschoal/ng-chat#59]

**Comment by rpaschoal** [comment]
Hi @aaithu-pk ,

Would you mind providing more details on your question/error?

Please follow the troubleshooting guidelines that can be found on the main README.

**Comment by aaithu-pk** [comment]
Just I want to know how to write myadapter

**Comment by rpaschoal** [comment]
Hi @aaithu-pk , have you read the README? There is a thorough walk-through on that written there.

If you can provide more details or even the code you're working around with, perhaps I can help you more with that.

Cheers!
