### ISSUE TITLE
How to upload a image and send as a message?

### ISSUE THREAD

**Issue by TarnjeetIron** [rpaschoal/ng-chat#62]
I am working on angular 6 app and I want to send a image/Doc as a message into chat. Can you please explain how to make it possible?

**Comment by rpaschoal** [comment]
Hi @TarnjeetIron,

This is not yet a feature of ng-chat. I am planning to implement this at some stage, but so far you are first user to request it.

What is your deadline on implementing this feature on your project?

Cheers!

**Comment by repdom** [comment]
> Hi @TarnjeetIron,
> 
> This is not yet a feature of ng-chat. I am planning to implement this at some stage, but so far you are first user to request it.
> 
> What is your deadline on implementing this feature on your project?
> 
> Cheers!

Actually I have the same issue. How can I implement it?

**Comment by rpaschoal** [comment]
Hi @repdom ,

This is not supported at the moment but it seems to be building up of people who needs this feature.

PR #69 is something I need to address first as a major refactory. I will keep you all posted here with an ETA for the file upload feature. I suggest whoever is interested in this feature sign up to this topic and post a "+1" message here requesting it.

Cheers!

**Comment by ajaynshd** [comment]
Hi 
Please add this feature to next release. I am also waiting for this.

**Comment by rpaschoal** [comment]
Hi @TarnjeetIron, @repdom and @ajaynshd 

I've just released 1.1.0 and it now supports the upload of files. I've added instructions on how to implement it on the [`README.md`](https://github.com/rpaschoal/ng-chat) file.

You can also check a sample implementation on the [ng-chat-nodejs](https://github.com/rpaschoal/ng-chat-nodejs) project

Let me know what you think of this recently implemented feature and if it is working for you. I've got plans to do some enhancements on top of it like image previewing from the chat window but this will be coming on subsequent releases most likely.

Looking forward to know what you think about it! Cheers!

**Comment by rpaschoal** [comment]
I'm closing this issue as the requested feature has been implemented and released.
