### ISSUE TITLE
Error on tap(click) on chat user name listmobile view. Mobile compatibility

### ISSUE THREAD

**Issue by LuisReinoso** [rpaschoal/ng-chat#71]
I'm try to open a chat when tap(click) on name of user chat, in google chrome's mobile view and google chrome mobile, and return an error "Cannot read property 'nativeElement' of undefined".

I search in your code and error occurs in [line 378 - ng-chat.component.ts](https://github.com/rpaschoal/ng-chat/blob/292c4cedba320be096a7bdcb251fa6a06157c0ca/src/ng-chat/ng-chat.component.ts#L378)

The tap(click) event trigger `openChatWindow(user, true, true)` function l[ine 10 - ng-chat.component.html](https://github.com/rpaschoal/ng-chat/blob/master/src/ng-chat/ng-chat.component.html#L10)
I see that it's depends of viewport, but this not to have to return an error. I don't understand why `this.chatMessageClusters.toArray()[windowIndex]`  it's undefined.

To have a mobile compatibility, could hide list of users (# ng-chat-people) and show windows and when hide window. show list of users.

Thanks.!

**Comment by rpaschoal** [comment]
Hi @LuisReinoso ,

I've just tried to reproduce it on the demo site and I can't. Could you please confirm if it happens to you on demo?

I've been considering hiding the friends list if there is no viewport space to display at least one chat window. 

Is that a big issue for you at the moment? I can add that to the queue for next release. We've got a few things planned to be implemented, I could add that on top.

Cheers!

**Comment by LuisReinoso** [comment]
I try to reproduce it in the live demo web page but not return any error.

This would be a nice feature.
>   I've been considering hiding the friends list if there is no viewport space to display at least one chat window.

I recorded my screen to you look the error: https://gifyu.com/image/NvBL. So isn't a big issue for me. 
What configuration of component will produce this error on my own implementation.

**Comment by rpaschoal** [comment]
Hi @LuisReinoso ,

This looks strange. I will implement the feature I've mentioned above in the next release so it shouldn't be a big issue for you in the future.

I will leave this thread open and update you as soon as a new version is released.

Cheers!

**Comment by ajaynshd** [comment]
Hi 
Please add this feature to next release. I am also waiting for this.

**Comment by ajaynshd** [comment]
Hi @rpaschoal 
Please add this feature to next release. I am also waiting for this.

**Comment by rpaschoal** [comment]
Hi @LuisReinoso and @ajaynshd 

Just updating you guys on this. I've got the fix for this but haven't release yet. There is a bunch of things that will come on next release including being able to upload files.

You can check the progress here https://github.com/rpaschoal/ng-chat/compare/development?expand=1

I'll keep this issue opened and let you know when the new release is out.

Cheers.

**Comment by rpaschoal** [comment]
Hi @LuisReinoso and @ajaynshd ,

I've just released 1.1.0 today and this is included. The friends list does not render if there isn't enough space for at least one chat window to be opened.

This behavior can be overridden using the `hideFriendsListOnUnsupportedViewport` which defaults to true at the moment.
