### ISSUE TITLE
send Attachments, links or images

### ISSUE THREAD

**Issue by Magneto2018** [rpaschoal/ng-chat#73]
Could you please add the functionality to send image, link or some attachment.
Thanks

**Comment by rpaschoal** [comment]
Hi @Magneto2018 ,

Links are already supported and converted automatically to hyper links when pasted and sent.

Attaching and sending files is upcoming on the next release and it will be the foundation for sending and previewing images (You will be able to send an image on the next version but it will go as a file attachment).

Cheers!

**Comment by rpaschoal** [comment]
Hi @Magneto2018 ,

I've just released 1.1.0 and it now supports the upload of files. I've added instructions on how to implement it on the [`README.md`](https://github.com/rpaschoal/ng-chat) file.

You can also check a sample implementation on the [ng-chat-nodejs](https://github.com/rpaschoal/ng-chat-nodejs) project

Let me know what you think of this recently implemented feature and if it is working for you. I've got plans to do some enhancements on top of it like image previewing from the chat window but this will be coming on subsequent releases most likely.

Looking forward to know what you think about it! Cheers!

**Comment by Magneto2018** [comment]
i can't see option to send attachment in chat window. and also unable to import "PagedHistoryChatAdapter", do i have to drag drop or there would be some icon? i can see in package there is "PagedHistoryChatAdapter" but i can't import it, it gives error.

**Comment by rpaschoal** [comment]
I'm closing this issue as the requested feature has been implemented and released.

**Comment by pattarmanjunath50** [comment]
Hi,
Is there a way to listen the click event on the message so that if there was a hyperlink referencing a component in the same application, can be redirected to that component in the application?
Please help.
