### ISSUE TITLE
Show the message date and time

### ISSUE THREAD

**Issue by Magneto2018** [rpaschoal/ng-chat#74]
Show the message date and time in messages history.

**Comment by rpaschoal** [comment]
The request feature will be shipped with version `2.0.0` which will be the next release.

**Comment by Vivekdude** [comment]
@rpschoal When version 2.0.0 is going to released, We just need to implement this functionality.

**Comment by rpaschoal** [comment]
Hi @Vivekdude ,

This is implemented at my current dev branch, just needs some more tests around it. I still have to implement the group chat which I haven't started.

I'll do my best to release the next version prior to the 27th of this month even if it does not include the group chat feature. I'll update you here once it has been released.

Cheers!

**Comment by Vivekdude** [comment]
ok Thanks @rpaschoal  Could please guide me to handle the User status like Online, Offline, away, how i supposed to handle that.

**Comment by rpaschoal** [comment]
Hi @Vivekdude ,

On your chat adapter instance you have a public method called `onFriendsListChanged`. You can just call it from your angular application and component that uses ng-chat. You would have to be notified by your application that handles the messages, so for example if you are using signalR you would send a message through the hub to the client and on the event of that message invoke `onFriendsListChanged` with the updated friends list.

There is also an option to use a polling mechanism for the friends list: `pollFriendsList`. Just search for that on the main README here.

**Comment by rpaschoal** [comment]
Hi @Magneto2018 and @Vivekdude ,

Just letting you know that this has been released with `2.0.0-rc.1`.

I haven't merged the changes on the master branch yet as this is an RC release so please refer to the README on this link for instructions on the new features: https://github.com/rpaschoal/ng-chat/tree/2.0.0-rc.1

I am planning on building a .net core application with a full demo of ng-chat and all its features, and only after that I'll be moving it to `2.0.0` as that will be a good opportunity for better testing and fine tuning of this release.

Cheers!
