### ISSUE TITLE
Errors onMessageReceived when user chat window is closed

### ISSUE THREAD

**Issue by Magneto2018** [rpaschoal/ng-chat#76]
I was testing the chat and got errors.
this happens when chat windows are closed and some one messaged you and window automatically opens with errors. if you have already opened the chat window for the user who is messaging you will not get error. if you get error on above situation you will always get error on **onMessageSeen** event.

**Comment by rpaschoal** [comment]
Hi @Magneto2018 ,

Would you be able to provide more details on the error message?

**Comment by Magneto2018** [comment]
![image](https://user-images.githubusercontent.com/36952430/46994958-0b1ebf80-d130-11e8-9ace-ee84e0eee630.png)

please see the attached screenshot, i think it is on messages parsing. maybe messages list is not correct or something else.

![image](https://user-images.githubusercontent.com/36952430/46995011-4de09780-d130-11e8-9dee-b7b6bf8b61bd.png)

![image](https://user-images.githubusercontent.com/36952430/46995056-7a94af00-d130-11e8-8311-319e78655e42.png)



See the screenshot below, problem is with status parsing
![image](https://user-images.githubusercontent.com/36952430/46995120-bd568700-d130-11e8-8635-1af8ea517d2b.png)

**Comment by Magneto2018** [comment]
in the above screenshot (last one) see the chat window status is not there for user.

**Comment by rpaschoal** [comment]
Hi @Magneto2018 ,

I've got a fix for "Cannot read property 'message' of undefined" on this commit: https://github.com/rpaschoal/ng-chat/commit/2f1f88ee0750471f87baba118cdb40af71d77975

Not sure on the other error, are you using a custom localization object?

**Comment by Magneto2018** [comment]
Nope i am not using localization.

**Comment by rpaschoal** [comment]
Hi @Magneto2018 ,

I've just released 1.1.0 and I believe it fixes this. Would you be able to test it against 1.1.0 and let me know if this is fixed? Cheers!

**Comment by Magneto2018** [comment]
Hi @rpaschoal  one error is fixed which one you mentioned, "Cannot read property 'message' of undefined" but the other one is still there, status.tostring is undefined. maybe my user object doesn't have status property but this should not happen, let me check and update here.
