### ISSUE TITLE
After adding NgChatModule to app.Module, project won't build

### ISSUE THREAD

**Issue by tcochrane1969** [rpaschoal/ng-chat#8]
All I did was intall ng-chat and then import into app module

ERROR in ./~/ng-chat/ng-chat/ng-chat.component.ts
Module not found: Error: Can't resolve ''

**Comment by rpaschoal** [comment]
Hi @tcochrane1969, would you be able to post here a jsfiddle reproducing that?

**Comment by tcochrane1969** [comment]
Hi rpaschoal,
I figured it out last night. I had updated my webpack and since all my other css was just bootstrap, I wasn't using any .css files.  When I added ng-chat you use .css files and my loader needed to change with the new version of webpack to css-loader.  Once I updated that everything started working.  Thanks.

**Comment by rpaschoal** [comment]
@tcochrane1969 I am glad you managed to sort it out. I will close this issue but feel free to open another one if you have any doubts or suggestions for this project.
