### ISSUE TITLE
ng build --prod error

### ISSUE THREAD

**Issue by kallklen** [rpaschoal/ng-chat#82]
Hi,
When I try to run the "ng build --prod" command, it returns the error: 

ERROR in node_modules\ng-chat\ng-chat.d.ts.ɵa.html(2,25): : Property 'unsupportedViewport' is protected and only accessible within class 'NgChat' and its subclasses.

"ng build" works fine.

**Comment by rpaschoal** [comment]
Hi @kallklen,

Thank you for reporting this. I will have a look into it, but just out of curiosity, do you need to compile TS under node_modules? Wouldn't you rather just use the compiled version that is distributed?

What version of typescript do you have?

**Comment by rpaschoal** [comment]
Hi @kallklen ,

Just an update on this... It seems that JIT compilation allows private/protected to be accessed on the template. This is not the case with AOT as it relies on Typescript itself and not on transpilation.

I will be working on a patch for this and releasing soon. I will update you as soon as the new patched version is available.

Cheers!

**Comment by rpaschoal** [comment]
Hi @kallklen ,

Thanks for pointing this out. I've deprecated `1.1.1` on NPM and released `1.1.2`. Could you please check if it is working now for you?

I still have my PR open here as I have to upgrade the CLI for the tests, but I've managed to run it locally using the old CLI and they've all passed hence why I've already published it to NPM as `1.1.1` was broken.

Please let me know if your issue has been sorted so I can close this thread. Cheers!

**Comment by kallklen** [comment]
Hi @rpaschoal,

It works now, thanks for the quick response.

Cheers!

**Comment by rpaschoal** [comment]
No worries @kallklen! Closing this issue as it has been fixed.
