### ISSUE TITLE
Get message using onMessageReceived

### ISSUE THREAD

**Issue by davidalisson** [rpaschoal/ng-chat#84]
Hi, 
I use in my project two chats, one for mobile app and one for web application (ng-chat). I need to the user receive a push notification on webapp when a client send a message.

I'm using Firebase RealTime Database for storage chat messages. I can get and send messages but I can't receive push notification when the mobile user send message to webapp user

**Comment by davidalisson** [comment]
Hi @rpaschoal, 
I can send and receive messages, I can also get them using `getMessageHistory` but I can't show a new message received instantly, I need to close the chat window and open it again to a new message sent by client appears.  I'm not using back-end to send and receive messages, I do this only on the front-end.
If nessessary I can show my adapter.

**Comment by rpaschoal** [comment]
It might be just your adapter implementation @davidalisson 

Before you post your adapter here as this might be sensitive information, have you had the chance to have a look at this project? It is a nodejs + ng-chat sample: https://github.com/rpaschoal/ng-chat-nodejs

If you run this project locally you can open 2 different browser sessions and send and receive messages across. Have a look at the adapter there and see if it helps you sorting out your current issue.

Cheers!

**Comment by davidalisson** [comment]
Hi @rpaschoal, can you put this sample in demo folder of the project? This content helped me a lot and can help another devs. Anyway, thanks for supporting me on this! Any doubt I'll be here again :rofl:

**Comment by rpaschoal** [comment]
Hi @davidalisson ,

Happy to know that you've managed to sort it out 🎉 

The link to the NodeJS example is right at the top of the README 😅
