### ISSUE TITLE
ERROR TypeError: Cannot read property 'triggerOpenChatWindow' of undefined

### ISSUE THREAD

**Issue by mukeshphpdev** [rpaschoal/ng-chat#88]
getting this ERROR TypeError: Cannot read property 'triggerOpenChatWindow' of undefined

calling from another component

**Comment by rpaschoal** [comment]
Hi @mukeshphpdev ,

It seems you are trying to use `IChatController` methods and your object instance is undefined. Looks to me that your `ViewChild` binding might be wrong.

**Comment by mukeshphpdev** [comment]
thanks
