### ISSUE TITLE
How to call OnUserClick directly from anywhere ?

### ISSUE THREAD

**Issue by bhaumikdarji** [rpaschoal/ng-chat#90]
Hi,

I can open friend chat window from anywhere.
But I want to open direct chat window for use to use  from anywhere.
Currently we have to click from Friend list only.
How to call it from anywhere?

**Comment by rpaschoal** [comment]
Hi @bhaumikdarji 

Have you tried using `IChatController` ? Check this section on the docs: https://github.com/rpaschoal/ng-chat#triggering-ng-chat-actions-from-elsewhere

Basically you need to get the instance of your chat and then you can just open a chat window for a user by calling `this.ngChatInstance.triggerOpenChatWindow(user);`

**Comment by rpaschoal** [comment]
Good to know @bhaumikdarji, cheers!
