### ISSUE TITLE
How to paginate through old messages

### ISSUE THREAD

**Issue by mukeshphpdev** [rpaschoal/ng-chat#94]
Hi @rpaschoal,

i am facing pagination issue, i want to load old messages when scroll up, is there any option for this.
currently i am using firebase,  can you give me any example for it.

**Comment by rpaschoal** [comment]
Hi @mukeshphpdev ,

There is an experimental adapter for this feature as mentioned on the README here https://github.com/rpaschoal/ng-chat#paged-history-chat-adapter-beta

Here is an example implementation: https://github.com/rpaschoal/ng-chat/blob/master/demo/offline_bot/src/app/demo-adapter-paged-history.ts

Hope it helps! Cheers

**Comment by mukeshphpdev** [comment]
thanks a lot.

Cheers
